package-lock.json, package.json, src/components/LeftSidebar/tabs/Awards.js, src/components/LeftSidebar/tabs/Certifications.js, src/components/LeftSidebar/tabs/Objective.js, src/index.css, src/shared/MarkdownHelpText.js, src/shared/TabBar.js, src/shared/TextArea.js, src/templates/gengar/Gengar.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js
- Implemented Markdown Support in Descriptions using `react-markdown`
- Added Descriptions to Awards & Certifications
- Fixed Email Overflow Issue #2 
- Organized Template Structure and Markup
=> Feature: Markdown

package-lock.json, package.json, public/index.html, src/components/App/App.js, src/components/LeftSidebar/LeftSidebar.js, src/components/LeftSidebar/tabs/Awards.js, src/components/LeftSidebar/tabs/Education.js, src/components/LeftSidebar/tabs/Extras.js, src/components/LeftSidebar/tabs/Languages.js, src/components/LeftSidebar/tabs/References.js, src/components/LeftSidebar/tabs/Skills.js, src/components/RightSidebar/RightSidebar.js, src/components/RightSidebar/tabs/Fonts.js, src/context/AppContext.js, src/index.css, src/shared/Counter.js, src/shared/TextField.js, src/templates/gengar/Gengar.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js, src/utils/index.js
- Added Languages & References Section
- Updated Onyx Template
- Updated Pikachu Template
- Updated Gengar Template
- Added Nunito Font, removed few others
- Added Entry Animation to App
=> Feature: New Resume Sections, Languages & References

src/index.css, src/templates/castform/Castform.js
=> Bugfix: Indentation & Castform

.eslintrc, src/assets/dummy/data.json, src/components/LeftSidebar/tabs/Awards.js, src/components/LeftSidebar/tabs/Certifications.js, src/components/LeftSidebar/tabs/Education.js, src/components/LeftSidebar/tabs/Extras.js, src/components/LeftSidebar/tabs/Languages.js, src/components/LeftSidebar/tabs/References.js, src/components/LeftSidebar/tabs/Work.js, src/context/AppContext.js, src/shared/Checkbox.js, src/shared/ItemActions.js, src/templates/castform/Castform.js, src/templates/gengar/Gengar.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js
This PR implements the issue request #11, the ability to hide/show individual items in an array.
This might cause older JSON structures to not display anything, but it can be solved by just enabling all the entries once.
=> Feature: Hide Individual Items

README.md, netlify.toml
Hi there 👋 Great site and beautiful resumes that it can generate :)
To make it easier for people to deploy their own site I added a "Deploy to Netlify" button in this PR (I am not affiliated with the Netlify. I just like their platform a lot). Unfortunately since the button deploys the site from the master branch of **your** repo, that means I can only test whether the button works correctly (I think it should) after you merge my branch. I will make sure I test it out if you decide to do so :)
=> Netlify button

docs/.vuepress/config.js, docs/changelog/README.md, package-lock.json, package.json, public/index.html, src/components/RightSidebar/tabs/About.js
- Updated Changelog
- Update Canonical URL in `index.html`
- Add Documentation Link in About Tab
=> Feature: Add Documentation Link in About Tab

.dockerignore, Dockerfile, Dockerfile-dev, docker-compose-dev.yml, docker-compose.yml, nginx/nginx.conf, package-lock.json, package.json
- Resolves Issue #29 
- **TODO:** Update Documentation on How to Use Docker
=> Feature: Dockerize App

src/shared/TabBar.js
add mouse wheel scroll into TabBar component for a better user experience
=> add mouse wheel scroll into tabBar

src/templates/castform/Castform.js
=> Fix castform template does not display skills heading properly

docs/contributing/README.md
This PR fixes a typo in Contributing
great work by the way 👍
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/amruthpillai/reactive-resume/63)
=> fix typo in Contributing

src/index.css, src/shared/TabBar.js
- fix bug with bullet points not appearing properly, resolves #76
=> Bugfix: Bullets are cut off in the exported PDF

.dockerignore
add additional files/folders that dont need to be in the Docker image
=> update dockerignore to exclude other unneeded folders/files

src/assets/demo/data.json, src/components/LeftSidebar/tabs/Languages.js, src/templates/castform/Castform.js, src/templates/celebi/Celebi.js, src/templates/gengar/Gengar.js, src/templates/glalie/Glalie.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js
- Update Language Tab to have both Level & Rating
- Updated Templates to show Level & Rating
=> Feature: Language Level & Rating

src/i18n/locales/vi/app/app.json, src/i18n/locales/vi/leftSidebar/awards.json, src/i18n/locales/vi/leftSidebar/certifications.json, src/i18n/locales/vi/leftSidebar/education.json, src/i18n/locales/vi/leftSidebar/extras.json, src/i18n/locales/vi/leftSidebar/languages.json, src/i18n/locales/vi/leftSidebar/objective.json, src/i18n/locales/vi/leftSidebar/profile.json, src/i18n/locales/vi/leftSidebar/references.json, src/i18n/locales/vi/leftSidebar/work.json, src/i18n/locales/vi/rightSidebar/about.json, src/i18n/locales/vi/rightSidebar/actions.json, src/i18n/locales/vi/rightSidebar/colors.json, src/i18n/locales/vi/rightSidebar/fonts.json, src/i18n/locales/vi/rightSidebar/settings.json, src/i18n/locales/vi/rightSidebar/templates.json
The translation is based on currently in use l10n strings, not the old ones left in those json files.
=> Add Vietnamese translation

docs/changelog/README.md, src/shared/Checkbox.js, src/shared/PageController.js
- Fix Issue with Page Controller Icon Size
- Fix Issue with Checkbox Icon Toggle
=> Bugfix: Icon Sizes and Visibility

docs/changelog/README.md, src/components/LeftSidebar/LeftSidebar.js, src/components/LeftSidebar/tabs/Hobbies.js, src/components/LeftSidebar/tabs/Skills.js, src/context/AppContext.js, src/templates/castform/Castform.js, src/templates/celebi/Celebi.js, src/templates/gengar/Gengar.js, src/templates/glalie/Glalie.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js
- Introduce Hobbies Section in all templates, resolves #141
- Add functionality to reorder Skills & Hobbies, resolves #139
=> Feature: Add Hobbies Section, Reordering Skills/Hobbies

src/i18n/locales/he/app/app.json, src/i18n/locales/he/leftSidebar/awards.json, src/i18n/locales/he/leftSidebar/certifications.json, src/i18n/locales/he/leftSidebar/education.json, src/i18n/locales/he/leftSidebar/extras.json, src/i18n/locales/he/leftSidebar/languages.json, src/i18n/locales/he/leftSidebar/objective.json, src/i18n/locales/he/leftSidebar/profile.json, src/i18n/locales/he/leftSidebar/references.json, src/i18n/locales/he/leftSidebar/work.json, src/i18n/locales/he/rightSidebar/about.json, src/i18n/locales/he/rightSidebar/actions.json, src/i18n/locales/he/rightSidebar/colors.json, src/i18n/locales/he/rightSidebar/fonts.json, src/i18n/locales/he/rightSidebar/settings.json, src/i18n/locales/he/rightSidebar/templates.json
app \ left sidebar hebrew translations
=> hebrew translations

src/i18n/locales/en/app/app.json, src/shared/ItemActions.js
=> delete button text was not translated

src/i18n/locales/pt/rightSidebar/settings.json
Just a little correction in translation to portuguese.
=> Fix portuguese translation word

src/assets/demo/data.json, src/components/LeftSidebar/tabs/Hobbies.js, src/components/LeftSidebar/tabs/Skills.js, src/context/AppContext.js, src/templates/castform/Castform.js, src/templates/celebi/Celebi.js, src/templates/gengar/Gengar.js, src/templates/glalie/Glalie.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js, src/utils/index.js
- Convert skill and hobby to objects, each object contains a unique key
- Fixed move and remove item does not work properly for eduction and skills page
=> Fix: move and remove items 

src/utils/index.js
- When clicked on save as pdf for too many times, too many files were downloaded
=> fix: Save as pdf saved downloaded too many files on multiple clicks

src/templates/castform/Castform.js, src/templates/glalie/Glalie.js
=> fix: Markdown style doesn't work in OBJETIVE section #183

src/i18n/locales/fr/app/app.json
Cancel was in German, I change it to French
=> [i18n ] Cancel was in German, I change it to French

src/assets/demo/data.json, src/components/LeftSidebar/tabs/Hobbies.js, src/components/LeftSidebar/tabs/Skills.js, src/context/AppContext.js, src/i18n/locales/fr/app/app.json, src/templates/castform/Castform.js, src/templates/celebi/Celebi.js, src/templates/gengar/Gengar.js, src/templates/glalie/Glalie.js, src/templates/onyx/Onyx.js, src/templates/pikachu/Pikachu.js, src/utils/index.js
@SHENG-X
- fix: Move and remove should match item by id … 0293ab6
- Merge branch 'develop' into fix-move-remove 49cc1d8
- chore: Using id in Skills and Hobbies … e2ed181
- fix: Save as pdf saved downloaded too many files on multiple clicks … e52537c
- fix: Markdown style doesn't work in OBJETIVE section #183 da98bf5
@Kafiil
- Update app.json … 909db6e
@AmruthPillai
- Merge pull request #180 from SHENG-X/fix-move-remove … aab6f00
- Merge pull request #182 from SHENG-X/fix-save-as-pdf … 97e2794
- Merge pull request #184 from SHENG-X/fix-objective-section-in-markdown … 2d80f0d
- Merge pull request #186 from Kafiil/patch-1 … ef9a1af
=> Assorted Bug Fixes from Open Source Community

src/components/LeftSidebar/tabs/Profile.js, src/templates/castform/Castform.js
=> [Feature] Option to change the value of the header in the Profile section

src/components/LeftSidebar/tabs/Profile.js, src/templates/castform/Castform.js
@bryannsi 
[Feature] Option to change the value of the header in the Profile section...
=> Option to change the heading for Profile

src/i18n/locales/pt-br.json
Did the translation for brazilian portuguese. I hope this helps you!
=> add brazilian portuguese language

src/i18n/locales/fr.json
I wrote fr.json. I left two items in english : sourceCode and translate
=> fr translation

src/i18n/locales/tr.json
Added full Turkish language support loyal to the original `en.json` file
=> Added Turkish language support

src/i18n/index.js, src/i18n/locales/index.js, src/i18n/locales/nl.json
=> add dutch translation

src/modals/sections/SkillModal.js
Replace skills level select by a simple input => allow more flexibility and all langage support for this fields
=> Customize skills level input

src/pages/index.js
Change "convinient" => "convenient"
=> Fix typo on the index page

src/i18n/index.js, src/i18n/locales/en.json, src/i18n/locales/index.js, src/i18n/locales/no.json
...and a single English typo I came across.
BTW, should line 225 from the translation say "LinkedIn" instead of "Reactive Resume"?
=> Add Norwegian translation

src/i18n/locales/pt-pt.json
Hello. I've come across your project and wanted to contribute. I've translated the English json file to Portuguese - Portugal (pt-PT). It's my very first contribution to an open source project. Hope everything is ok and I didn't mess up anything! 
Cheers!
=> Translation to pt-PT

src/modals/sections/ProjectModal.js, src/templates/blocks/Projects/ProjectsA.js
fixes #326 
Added an end date field to projects and relabeled the date field as the start date in the front end, so this is backwards compatible.
=> Add end date field to projects

src/modals/sections/SkillModal.js
=> Fix #441: Make Skill Level Optional

src/components/builder/lists/List.js, src/components/builder/lists/ListItem.js, src/pages/app/__tests__/builder.skills.test.js, src/pages/app/__tests__/helpers/builder.js
Added support for drag & drop to the List component. Fixes #428 .
All sections using the List component (Skills, Hobbies, Certifications, Projects, etc.) will now support drag & drop.
=> Add support for drag & drop to the List component

src/pages/index.js
Awesome product, thanks for making it FOSS!
=> fix link to product hunt

README.md, gatsby-config.js, src/i18n/index.js, src/i18n/locales/index.js, src/i18n/locales/lt.json, src/utils/dayjs.js
Found this tool yesterday and I think it's awesome. Decided to contribute by translating it to my native tongue.
=> Added Lithuanian translations.

src/i18n/locales/fr.json
Hi!
I've fixed a translation error ("Punaise" is a french word that refers to a real bug, with legs and all that kind of stuff) and I also changed some words and punctuations marks that I found more relevant.
Feel free to ask me anything regarding this commit!
=> Updating FR.json translations

src/modals/DataModal.js
=> Fixed bug where multiple resumes are created if "Create Resume" button is spammed

src/i18n/locales/de.json
Changed translation of present to a more CV suitable
=> Improvement of German Translation

src/i18n/locales/de.json, src/i18n/locales/en.json, src/templates/Gengar.js
The contact heading in Gengar theme was hardcoded in english. I added the possibility to translate it.
Also reworked the german translation.
=> Add translation for "Contact" in Gengar theme.

src/templates/blocks/Contact/ContactA.js, src/templates/blocks/Icons.js, src/utils/dayjs.js
added a single line address to pikachu with FA icon
=> Pikachu address

README.md
I had to think a bit about what values to put in the .env file, and once I figured it out, I thought it would be helpful to add that information explicitly in the readme so other developers could speed up local development.
=> add information on setting up firebase to the readme

src/components/builder/left/LeftSidebar.js, src/components/builder/lists/ListItem.js, src/components/builder/right/RightNavbar.js, src/components/builder/right/RightSidebar.js, src/contexts/SettingsContext.js, src/pages/app/builder.js, src/pages/app/builder.module.css, src/styles/global.css
1] people faced trouble seeing their resume changes, so I added a feature to toggle both left and right sidebars so users can have a bigger view of their resume.
2] sometimes users might accidently delete any of their list items so asking for confirmation before deletion is a must so I have added that.
=> 1] sidebar toggle feature 2] ask for confirmation before delete operation

gatsby-config.js, package.json
As pnpm considerably faster than npm, i add some change to enable using pnpm.
=> Add ability to build using pnpm

README.md, docs/docs/index.mdx
Very trivial. But still, here's my contribution! 😄 
After all, grammar is very important in resumes. 😉
=> Fixed a Typo in README

client/components/build/RightSidebar/sections/Theme.tsx
=> Fix-Crash on Entering Primary Color Hex Code without # Prefix

README.md, docs/docs/index.mdx
Linked the `Version badge` to **Releases** and `License badge` to **MIT License**.
=> Linking Badges to Releases & License

client/templates/Castform/widgets/Masthead.tsx, client/templates/Gengar/widgets/Masthead.tsx, client/templates/Glalie/widgets/Masthead.tsx, client/templates/Kakuna/widgets/Masthead.tsx, client/templates/Onyx/widgets/Masthead.tsx, client/templates/Pikachu/widgets/Masthead.tsx
=> Fixed URL 404 issue in Profile Section URL

client/components/shared/BaseModal.module.scss
Fix- #795 
Change- Made Changes in BaseModal Css, hid the scrollbar for good looking UI and Made the Header and Footer Sticky for good UX
=> Fix-#795 No Scoll Behaviour on Overflow

.github/workflows/docker-build-push.yml
Only build once for every client and server, resulting same image on both repo image.
=> combine-tags

client/modals/auth/LoginModal.tsx
Signed-off-by: SRIHARI S <sshsrn@gmail.com>
=> Updated login modal

client/public/locales/hu/builder.json, client/public/locales/hu/common.json, client/public/locales/hu/dashboard.json, client/public/locales/hu/landing.json, client/public/locales/hu/modals.json
The original translation was machine-generated, with many grammatical and stylistic errors that showed up not just in the application but in the resume content as well.
=> fixed grammatical and stylistic errors in Hungarian translation

client/public/locales/de/common.json
Hi
tiny translation error to German
In this context it's a lower case, not upper case.
=> Update common.json - tiny translation error to German

client/components/build/RightSidebar/sections/Layout.tsx, client/components/build/RightSidebar/sections/Settings.tsx, client/config/languages.ts, client/public/locales/de/builder.json, client/public/locales/de/common.json, client/public/locales/de/dashboard.json, client/public/locales/de/landing.json, client/public/locales/de/modals.json, client/public/locales/en/builder.json
BREAKING CHANGE: locales without the new fields will display the field name
=> fix: made some missing texts translatable

server/src/printer/printer.service.ts
Resolve #1122, ensure personal image loaded before pdf generate.
=> Fix: wait for networkidle event to ensure image load

client/utils/date.ts
=> Add ISO 8601 option

client/components/build/LeftSidebar/LeftSidebar.tsx, client/components/build/LeftSidebar/sections/Section.tsx, client/components/shared/Heading.tsx, client/config/languages.ts, client/modals/builder/sections/WorkModal.tsx, client/next-i18next.config.js, client/public/locales/pt-BR/builder.json, client/public/locales/pt-BR/common.json, client/public/locales/pt-BR/dashboard.json, client/public/locales/pt-BR/landing.json, client/public/locales/pt-BR/modals.json, client/utils/date.ts
- Adding pt-BR translation file
- Fixing all sections translate that wasn't working
- Fix formatDate error that was subtracting one day from the date
=> Translation fixes on LeftSideBar

client/templates/sectionMap.tsx
=> Fix issue when a section is duplicated/cloned, ID is null

apps/client/src/pages/dashboard/resumes/_layouts/list/_components/resume-item.tsx
Hey,
The Functionality of the Copy Link was missing.
Kindly review and merge the same.
=> Bug Fix for 1569 - `On Dashboard in List View Lock Menu missing`

apps/client/src/pages/dashboard/resumes/_layouts/list/_components/resume-item.tsx
Missed the dropdown in last, Fixed here.
=> BUG-1569 - Add Lock Option for List View

apps/client/src/components/locale-combobox.tsx, apps/client/src/components/locale-switch.tsx, apps/client/src/pages/dashboard/settings/_sections/profile.tsx, apps/client/src/pages/home/sections/faq/index.tsx, package.json, pnpm-lock.yaml
=> fix: implement fuzzy search with locale switcher and settings page

apps/client/src/pages/builder/sidebars/left/sections/shared/section-dialog.tsx
=> fix: modify z-index for dialogs to fix popover being hidden

apps/client/vite.config.ts
=> fix(vite): fix .po file loader issue

libs/parser/src/linkedin/index.ts, libs/utils/src/namespaces/csv.ts
Fixes #1604 see [this implementation comment](https://github.com/AmruthPillai/Reactive-Resume/issues/1604#issuecomment-1891743314)
=> fix(import): LinkedIn Profile.csv parsing fixes

apps/artboard/src/templates/bronzor.tsx, apps/artboard/src/templates/chikorita.tsx, apps/artboard/src/templates/ditto.tsx, apps/artboard/src/templates/gengar.tsx, apps/artboard/src/templates/glalie.tsx, apps/artboard/src/templates/onyx.tsx, apps/artboard/src/templates/pikachu.tsx, apps/artboard/src/templates/rhyhorn.tsx
Related Issue: https://github.com/AmruthPillai/Reactive-Resume/issues/1746
=> fix(templates): Vertical-align-top instead of vertical-align-middle entry header data

apps/client/src/pages/dashboard/resumes/_dialogs/import.tsx
=> fix(import): Changing 'Filetype' clears the 'File' upload field properly

libs/dto/src/user/user.ts
There are a lot of 2-character names in China.
=> modify the name field to a minimum of 2 characters

apps/client/src/pages/builder/sidebars/right/sections/theme.tsx
=> Fix popover stacking in right sidebar theme section

apps/server/src/auth/strategy/github.strategy.ts
=> fix(github_auth): fix GithubStrategy not searching for user using username

libs/ui/src/components/combobox.tsx, package.json
=> Add CommandList to Combobox component

apps/client/src/pages/builder/sidebars/left/dialogs/profiles.tsx
fixes : #1800 
https://github.com/AmruthPillai/Reactive-Resume/assets/73944177/3c4497a2-0a36-49a5-ab42-c444aeebad4f
=> debounce in profile icon

apps/artboard/src/templates/chikorita.tsx
=> fix(template): double issuer name in chikorita certificates

apps/client/src/pages/builder/sidebars/left/sections/picture/options.tsx
Bug fix for issue log:
https://github.com/AmruthPillai/Reactive-Resume/issues/1902
=> fix(client): fix Type Error in Picture Configuration Options

meta/privacy-policy.md
Replace [insert contact email] with hello@amruthpillai.com
=> fix(docs): Update privacy-policy.md
