AmruthPillai/Reactive-Resume

src/components/RightSidebar/RightSidebar.js, src/components/RightSidebar/tabs/About.js, src/components/RightSidebar/tabs/Actions.js
Requested by @nikolaos-spyratos in #7
- Added About Tab to the Right Sidebar
This will make it easier for people to find the GitHub Repo or raise an issue from within the project.
=> Feature: About Tab

src/context/AppContext.js
This fixes  issue #9 by using the data from the initial state for sections missing in the imported data.
=> Use initial state for section missing in an import.

src/templates/gengar/Gengar.js
Hey there! Cool app, I'm already making use of it.
Regarding Gengar theme. Content in CertificationItem wont wrap if too long, which results in ugly looks, if you put something too long there, like an URL for instance.
As a work around, I've put tailwind's "break-words" there, which seems to fix for CertificationItem. 
Original:
Fixed:
=> [Workaround] Gengar: Break line when CertificationItem p content is too long.

src/i18n/index.js
I suggest using the language names as written in their own languages, e.g. German -> Deutsch, Korean -> 한국어, Vietnamese -> Tiếng Việt, etc.
=> Add Vietnamese to the list as "Tiếng Việt"

src/i18n/locales/en/leftSidebar/languages.json, src/i18n/source/leftSidebar/languages.json
Currently the label is displayed as "languages.level.label".
=> Add level.label string

src/context/AppContext.js
- Using set on the shallow copy of the state object caused reducer called twice; reducer function should be pure; use deep copy of the state instead of shallow copy
=> fix: Reducer called twice due to use set on shallow copy of the state

src/components/builder/center/Artboard.js
Fix #248
It seems to cut off the text if it over resolution width 1680.
So if over 1680, add `transform-origin`.
I'm beginner of frontend development.
Please do not hesitate fix this PR.
=> Fix scaling for large monitor

src/templates/blocks/Contact/ContactA.js, src/templates/blocks/Contact/ContactB.js
The icons for phone, website, and email were already imported into the application and ready to use, but they hadn't been applied to the contact slots. I've added them in the same contact areas the other icons are used (such as GitHub, Twitter, etc.)
=> Set contact icons for phone, website, and email

src/components/builder/lists/List.js, src/modals/DataModal.js, src/templates/blocks/Education/EducationA.js, src/templates/blocks/Work/WorkA.js, src/utils/index.js
Fixes #336, #331, #301 
Hooks should only be called from the [top-level of React Function Components or custom Hooks](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level), which is why there have been various crash issues reported.
This PR is a quick-fix to prevent severe crashes, but there is likely a more elegant solution that can be submitted in a follow-up PR
=> Fix app crashes after setting date range

src/i18n/locales/fr.json
In french a "Cadeau" is a gift or a present. We use "Aujourd'hui" instead of "Cadeau" ^^
=> :bug: Fix translate mistake

src/components/builder/right/RightSidebar.js, src/components/builder/right/sections/FontSizes.js, src/data/fontSizeVarsDefault.js, src/data/rightSections.js, src/i18n/locales/en.json, src/styles/tailwind.css, src/templates/blocks/Awards/AwardsA.js, src/templates/blocks/Certifications/CertificationsA.js, src/templates/blocks/Education/EducationA.js, src/templates/blocks/Hobbies/HobbiesA.js, src/templates/blocks/Languages/LanguagesA.js, src/templates/blocks/Languages/LanguagesB.js, src/templates/blocks/Projects/ProjectsA.js, src/templates/blocks/References/ReferencesA.js, src/templates/blocks/References/ReferencesB.js, src/templates/blocks/Skills/SkillsA.js, src/templates/blocks/Work/WorkA.js
Added an ability to customize font sizes. This is set at a new section in the settings.
The controler for this sets a number of css variables which are used in css rules that
override tailwind's text-<size> to use the font size and line spacing contained in the
variable. The control itself is a simple logarithmic slider that controls a "scale
factor" by which all the text sizes in a resume are scaled by.
Fixes #379 #325 #256
=> Add ability to customize font size

gatsby-config.js
You can see that second letter in each group looks slightly different because glyphs are missing and it's falling back to default font.
After adding latin-ext glyphs it looks much better:
=> Add latin-ext subset to fix special characters missing in webfonts

src/i18n/locales/pl.json
- projects: typo fix
- birthDate: second word was incorrect
- technically it is correct, but "Wczytywanie" is more common translation for this
=> Improvement of polish translations

functions/index.js, src/components/builder/right/sections/Settings.js, src/contexts/UserContext.js
Fixes #466 
<br>
Changes applied to the `deleteUser` Firebase cloud function:
- Performance improvement: filtering by userId when retrieving the resumes from the database
- Added removal of the user node
- Deletions of resumes and user done through a single atomic update (all or nothing)
Changes applied to the UserContext `deleteAccount` function:
- Performing user re-authentication, if user is signed in with Google, as a very first step. This is done to prevent possible 'auth/requires-recent-login' errors later on, when `currentUser.delete()` is called. Should an error occur in the re-authentication, then the app will notify the user and will not proceed further
- Using `await` when calling the `deleteUser` Firebase cloud function. Should an error occur in the cloud function then the app …
=> Delete Account: fix for Firebase cloud function and error handling improvements

functions/index.js
1. "Download PDF" action: basic retry mechanism
This hopefully resolves #487, resolves #484, resolves #483, resolves #452, resolves #409, resolves #399, resolves #383, resolves #361.
I could reproduce the issue with the "Download PDF" action in my local tests. I was getting the "The cloud function is running into some trouble..." toast and in the browser console the "Access to fetch ... blocked by CORS policy ..." error, as mentioned in #487.
For me, changing the Puppeteer call `page.goto(url, { waitUntil: 'networkidle0' })` to `page.goto(url, { waitUntil: 'networkidle2' })` made it work. So the `printResume` Firebase cloud function has been modified to perform a basic retry mechanism: first try with `waitUntil` parameter set to `networkidle0`, if that fails try with `waitUntil` parameter …
=> "Download PDF" action: basic retry mechanism - "Delete Account" action: deletion of uploaded photographs

src/i18n/locales/pl.json
Corrected a few minor mistakes such as too many whitespaces or typos, e.g.
**Projects** - Ptojekty (should be Projekty)
**Education** - Wyksztłacenie (should be Wykształcenie)
"CV" should be written in capital letters, it was inconsistent
=> Correcting typos in pl.json

src/modals/sections/EducationModal.js, src/modals/sections/ProjectModal.js, src/modals/sections/WorkModal.js
We could probably even update this to something a bit more recent like 2018, depending on the context, but happy to leave the decision up to you.
=> fix typo in placeholder dates

src/modals/sections/ProjectModal.js, src/templates/blocks/Projects/ProjectsA.js
Sometimes, projects are ongoing, and it would be helpful to be able to show that, similar to how it's done in the Work section.
This is what's expected in the `formatDateRange` function, and it's more consistent with the way things are done in other parts of the application.
=> update Project data model to use "Present" if no end date selected

package-lock.json, package.json, src/components/shared/Markdown.js, src/pages/app/dashboard.js, src/styles/global.css, src/templates/Pikachu.js, src/templates/blocks/Awards/AwardsA.js, src/templates/blocks/Certifications/CertificationsA.js, src/templates/blocks/Education/EducationA.js, src/templates/blocks/Objective/ObjectiveA.js, src/templates/blocks/Projects/ProjectsA.js, src/templates/blocks/References/ReferencesA.js, src/templates/blocks/References/ReferencesB.js, src/templates/blocks/Work/WorkA.js
I wanted to add some table display of the technologies used for a project but commonmark doesn't support tables
Add gfm (Github Flavored Markdown) plugin to ReactMarkdown renderer
Launch the project from this branch, inside a section fill a markdown table, it should display properly
| a | b | c |
| - | - | - |
| e | f | g |
=> feat(markdown): add gfm support

README.md, src/i18n/index.js
Fix translation of "Japanese" in the language support list.
日本人 means Japanese person/people
日本語 means the Japanese language
=> fix translation error for language Japanese

src/templates/Castform.js, src/templates/Glalie.js
Image without 'object-class' class on profile picture div in template, stretches.
Image with 'object-class' class on profile picture div in template. No stretching.
Only impacting two templates
=> add 'object cover' class to templates that have issues with profile image stretching.

package.json
This enable dockerized reactive resume to bind network correcly, as docker `localhost` that gatsby usually use only work to docker container itself.
=> use -H 0.0.0.0 on Gatsby

client/templates/Gengar/Gengar.tsx
This is a Fix for a UI Bug which can be Observed in Gengar Template where Icons disappear on Primary Color Change
Follow Steps below to Replicate:
1- Select Template Gengar
2- Fill Email, Mobile details
3- Now Change the Primary Color
4- Keep the Background Color as #ffffff
You will observe that the Icons for Email, Mobile, etc in the MastHead will disappear
Reason: The Icon Color is being overwritten by the Background Color
=> Fix-Gengar Theme MastHead Icons Disappear on Theme/Primary Color Change

client/modals/builder/sections/SkillModal.tsx
This is a fix for an Overlapping in the Label "Disable" & "Beginner" text in the Slider Component in Skills Modal Sheet.
The issue was occurring because of more padding around the component.
=> Fixed Near Overlapping of "Disable" & "Beginner" Label Text in Skills Modal for Desktop Screen

client/templates/Castform/widgets/Section.tsx, client/templates/Gengar/widgets/Section.tsx, client/templates/Glalie/widgets/Section.tsx, client/templates/Kakuna/widgets/Section.tsx, client/templates/Onyx/widgets/Section.tsx, client/templates/Pikachu/widgets/Section.tsx
Issue - When user enters the "Website" in Work Experience and enters it without http or https, on clicking on that link, the user gets routed to 404 Page
This issue exists in all 6 templates currently
Fix- Added addHttp(url) in link prop in Section.tsx files of all the 6 templates
=> Fix - Work Experience Website Link Redirects to 404 if manually entered without http/https

client/templates/Pikachu/widgets/Masthead.tsx
Issue - Pikachu Theme Basic Details - Phone number, Email & Website are Center Justified as Shown Below which looks Asymmetric
Fix- Changed the css to _justify-items-left_ from _justify-items-center_
=> Fix-Pikachu Masthead Basic Details looks asymmetric Due to Centred Alignment

client/modals/builder/sections/PublicationModal.tsx
Issue- Publication Modal Screen Label Text Incorrect as in the Image Below
Fix- Removed the Double Quotes wrapping the Variable
=> Fix- Publication Modal Label text

client/modals/builder/sections/LanguageModal.tsx
Issue- As Shown in the Image Below
Fix- Similar to #667
=> Fix- Language Modal Slider Component Label Text Overlapping

client/styles/pages/Preview.module.scss
Issue- Resume when shared as Link, and viewed on Mobile Devices is not Scrollable to the left ( towards left sidebar )
Fix- Minor Changes the Preview.module.scss file
=> Fix- Resume Shared is not Scrollable on Phone Screen

docs/docs/index.mdx
Doc had a link to itself probably because it's a copy of README.
Modified & linked to the GitHub Repo so that they can check out this repo.
If you got some other important link, feel free to change. 🙂
=> Removed Self Referring Link in Docs

docs/package.json
on `pnpm dev` , docusaurus not conflicted with client because it set port on launch.
`docusaurus start --no-open --port 3200`
But on `pnpm start` client and docusaurus conflict each other, as the command not define port.
`docusaurus serve`
this PR add port to docusaurus, so `pnpm start` can run correctly.
`docusaurus serve --port 3200`
=> Update docusaurus to prevent crash with client

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
To avoid clutter & increase readability of issues, I suggest commenting out the extra help tips so that they don't appear in the actual issue report. 📝
I hope this is what you wished to implement with those additional help tips, which is supposed to help the issue authors only. 🙂
Don't see many using the template actually. 😅
=> Cleaned Issue Templates Using Comments

.github/workflows/docker-build-push.yml
Uses QEMU and Buildx to make the Docker image available on ARM platforms (can be extended to linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6).
ARM is a must for the convenience of Raspberry Pis :)
=> Automatic multi-platform Docker image build

server/src/health/health.controller.ts
This forces the backend to continuously call home and break if no response is received
this will fix #963
=> Removed Check on hard coded urls

server/src/integrations/integrations.service.ts
This fixes #1048.
Turns out the issue was that though an invalid archive is not empty, it cannot be closed and this was crashing the server.
=> Fix server crash when non-zip file is uploaded

.gitignore, client/components/build/LeftSidebar/LeftSidebar.tsx, client/components/build/LeftSidebar/sections/Section.tsx, client/config/sections.tsx, client/modals/auth/LoginModal.tsx, client/modals/builder/sections/WorkModal.tsx, client/public/locales/en/builder.json, client/store/modal/modalSlice.ts, client/store/resume/resumeSlice.ts, client/templates/sectionMap.tsx, schema/src/section.ts, server/src/resume/data/defaultState.ts
I would like to open this PR as a discussion on how to better arrange work experiences along multiple pages.
I have added a button "Add new section" under the current "work" section that adds a work-1, work-2 and so on sections.
I have modified the WorkModal to work with changing path (similar to the custom sections).
Please let me know what you think.
https://gfycat.com/thesesecretamericanratsnake
=> feat: additional work sections

client/components/build/LeftSidebar/LeftSidebar.tsx, client/components/build/RightSidebar/RightSidebar.tsx
If "Show scroll bars" is set to "Always" in the mac settings. Sidebars scroll horizontally all the time. Setting overflow: auto fixes the bug
=> fix: overflow-y-auto

client/templates/Gengar/widgets/Section.tsx
There seems to be a small bug in the Gengar template. If I select skills in two columns, I see the following picture
This seems to be a better option
=> fix: Gengar two cols bug

client/utils/template.ts
First time contribution (ever, woo!).
Fixes issue: #1165
Adds a check in ```addHttp()``` to see if ```mailto:``` or ```tel:``` is present before attempting to append ```http://```.
Thanks!
=> Fixing unconditional ```http://``` prefix.

client/templates/Castform/widgets/Masthead.tsx
Using the Castform template without a summary, still has extra whitespace for the summary. This commit fixes the extra whitespace to not appear when no summary is present.
Closes #1194
Before:
After:
=> fix: extra whitespace in Castform header

client/components/shared/ResumeInput.tsx
Closes [1371](https://github.com/AmruthPillai/Reactive-Resume/issues/1371)
**Expected behavior:** User should be able to select a year, then a month, and then a day. Also should change the date through keyboard.
**Found behavior:** After selecting the year it breaks the UI, renders the calendar in the corner of the screen instead of rendering with respect to the `Date of Birth` element and the user can't select the follow-up month and date properly.
Also when changing the date by arrow key, it stopped working after the first time and remove the focus from the element.
=> Fixed date selection by selecting month after year

client/utils/date.ts
Fixes https://github.com/AmruthPillai/Reactive-Resume/issues/1388
**Expected behavior:** When entering a date on any given Date Field, it should show date as it was selected.
**Found behavior:** Selected date is being converted to local date string.
=> Fixed Date entered on any <Date> field is one day earlier

client/modals/builder/sections/EducationModal.tsx
Expected behavior: In the education modal, the user should be able to select a year, then a month, and then a day. Also should change the date through the keyboard.
Found behavior: After selecting the year it breaks the UI, renders the calendar in the corner of the screen instead of rendering with respect to the Date Range element and the user can't select the follow-up month and date properly.
Also when changing the date by arrow key, it stopped working after the first time and remove the focus from the element.
=> fix: Education Date picker modal UI component

client/modals/builder/sections/WorkModal.tsx
Expected behavior: In the work modal, the user should be able to select a year, then a month, and then a day. Also should change the date through the keyboard.
Found behavior: After selecting the year it breaks the UI, renders the calendar in the corner of the screen instead of rendering with respect to the Date Range element and the user can't select the follow-up month and date properly.
Also when changing the date by arrow key, it stopped working after the first time and remove the focus from the element.
=> fix: Work Modal Datepicker popup

client/components/build/LeftSidebar/sections/PhotoUpload.tsx, server/src/resume/resume.service.ts
This pull request addresses problem #1460 by modifying the `updatedAt` value within the resume table. It now gets updated whenever a user deletes or uploads their resume photo. Additionally, the front-end also synchronizes with this change. Consequently, whenever a change in the image occurs, the `lastUpdatedAt` query parameter in the API is automatically adjusted, triggering the generation of a new PDF download.
=> fix: update the `updatedAt` field while deleting/uploading images

client/components/build/RightSidebar/sections/Settings.tsx, client/public/locales/en/builder.json
This pull request addresses the feature request mentioned in #1458 by improving the description of page breaks. Previously, page breaks were displayed correctly for both Letter size and A4 size, but this information was not reflected to the user when a different page format was selected. This update only fixes it for English language.
Changes in this pull request:
- Improved the description of page breaks to indicate the size of the page (Letter or A4).
=> Update break line description when page size is changed

client/services/resume.ts, server/src/printer/printer.service.ts
A partial fix for #1431, addresses some of the issues I found in #1431
I implemented url encoding for the secret key that `printer.service.ts` supplies to the Client when generating a pdf version of a resume.
I generated my secret key using `openssl rand -base64 32` which appends an = at the end.
Anyone else also using special characters would also encounter this issue.
The secret key not being encoded caused the Client to not accept it, therefore it refused to display a private resume which ultimately caused a 504 Gateway timeout error.
=> Fix for #1431

client/package.json, pnpm-lock.yaml
The recent bump by dependabot of next to 13.5.0 caused `pnpm install` to fail with:
```bash
WARN  GET https://registry.npmjs.org/next/-/next-13.5.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
```
It seems `13.5.0` is kinda of an empty / ghost version https://www.npmjs.com/package/next/v/13.5.0
It doesn't even have a readme and npm says it has 0 installs.
Solution:
Bumping next to 13.5.6 fixes the issue.
=> Fix: Bumping next to 13.5.0 broke pnpm install

.env.example
Add examples for `GITHUB_CALLBACK_URL` and `GOOGLE_CALLBACK_URL`
Took me a while to figure them out.
=> [v4]docs: Add example of oauth callback url

apps/client/src/pages/builder/_components/toolbar.tsx
Hey,
The Functionality of the Copy Link was missing.
Kindly review and merge the same.
=> Bug Fix for 1566 - `Copy Link to resume Icon not working on Builder Toolbar for Public Resumes`

apps/client/src/components/copyright.tsx
In Reactive-Resume/apps/client/src/components/copyright.tsx , there is a broken link to the projects readme. I changed it from https://github.com/AmruthPillai/Reactive-Resume/blob/main/LICENSE to https://github.com/AmruthPillai/Reactive-Resume/blob/main/LICENSE.md .
I found this issue using [link-inspector](https://github.com/justindhillon/link-inspector). If you found this PR useful, give the repo a star ⭐
=> Fixed broken link to LICENSE

apps/server/src/config/schema.ts, apps/server/src/storage/storage.service.ts
I've implemented an `STORAGE_SKIP_CREATE_BUCKET` env variable to skip the process of checking if the storage bucket exists.
For self-hosting I wanted to provide very limited S3 credentials to the api. However, doing `this.client.bucketExists()` requires at least `s3:HeadBucket` permissions. This would be straightforward in AWS or Minio, but this becomes problematic when using a [Cloudflare R2](https://developers.cloudflare.com/r2/) bucket which doesn't provide granular permission controls. This also might be the case for other S3 compatible providers.
Furthermore, if the bucket is manually provisioned beforehand the check is redundant.
Not quite sure if `STORAGE_SKIP_CREATE_BUCKET` would be the correct name though, `STORAGE_SKIP_BUCKET_CHECK` could be better. I would appreciate feedback …
=> Add option to skip storage bucket check & creation in storage service

apps/client/src/pages/builder/sidebars/left/dialogs/custom-section.tsx, apps/client/src/pages/builder/sidebars/left/dialogs/interests.tsx, apps/client/src/pages/builder/sidebars/left/dialogs/projects.tsx, apps/client/src/pages/builder/sidebars/left/dialogs/skills.tsx, apps/client/src/pages/builder/sidebars/left/sections/shared/section-dialog.tsx, libs/ui/src/components/badge-input.tsx
This PR is intended to try and address my suggestion here: https://github.com/AmruthPillai/Reactive-Resume/issues/1720
For each of the `dialog` components that allow a `Keyword` to be input, including:
* [custom-section](https://github.com/AmruthPillai/Reactive-Resume/blob/main/apps/client/src/pages/builder/sidebars/left/dialogs/custom-section.tsx)
* [interests](https://github.com/AmruthPillai/Reactive-Resume/blob/main/apps/client/src/pages/builder/sidebars/left/dialogs/interests.tsx)
* [projects](https://github.com/AmruthPillai/Reactive-Resume/blob/main/apps/client/src/pages/builder/sidebars/left/dialogs/projects.tsx)
* [skills](https://github.com/AmruthPillai/Reactive-Resume/blob/main/apps/client/src/pages/builder/sidebars/left/dialogs/skills.tsx)
If an input was typed by the user, but …
=> [Bugfix] Save Pending Keyword Input

libs/parser/src/linkedin/schema/profile.ts
Add some default values to the LinkedIn data import in case of missing data. Default values used in place of optional data in order to minimize changes to other parts of the codebase; since optionals require an extra step to handle.  Default values of whitespace might work better, but I cannot test to be sure.
Closes: #1604
=> Update profile.ts to add default values

package.json
Running the app locally failed for me, as I was on 18.12.0 and per Sharp's documentation, https://sharp.pixelplumbing.com/install#prerequisites, it requires a minimum of 18.17.0+. Once I upgraded to the latest 18 (18.19.1) everything worked fine.
=> Update minimum node to 18.17.0

libs/ui/src/components/rich-input.tsx
If the maintainers of Reactive Resume agree with the points raised in my issue here:
https://github.com/AmruthPillai/Reactive-Resume/issues/1726
This PR will configure [Tiptap](https://tiptap.dev/) to behave similar to other text editors when adding hyperlinks.
---
I will note that this may negatively impact users who wish to add text _after_ adding a hyperlink to the editor:
And as such, I will understand if the Reactive Resume maintainers see this as an overall negative change.
=> [Bugfix] Instantiate Link with inclusive set to false

apps/artboard/src/pages/artboard.tsx, apps/artboard/src/styles/main.css
The typography option toggle class were added in the DOM #root but when the server is printing the resume, a child section of the DOM #root is cloned and inserted for pdf processing which misses out the Typography option toggle class in the parent DOM, resulting in the bug, Thus, the same class were added to each cloned DOM node (a node for each page DOM with [data-page] attribute).
=> fix(#1750): fixed downloaded PDF have issue(s) with Typography options

apps/artboard/src/styles/main.css
In Gengar template the link for personal project was overflowing out of sidebar so added a little CSS to fix the issue 
please see images attached below to get more clarity on issue and fix
This PR is for issue #1764 
Issue:
Fix:
=> fix(gengar template): link of personal project was overflowing outside.

tools/compose/simple.yml
Implements the fix proposed in #1754 
This PR updates the`STORAGE_URL` for the `simple.yaml` Compose setup that has no reverse proxy, by adding the bucket name as a URL suffix. Without it, PDF downloads don't work.
=> fix issue where PDF downloads fail on compose setup

apps/server/src/config/schema.ts
As per the code restriction specified in the configuration schema,  the `SMTP_URL` was required to start with `smtp://`.
https://github.com/AmruthPillai/Reactive-Resume/blob/fe77b14807873efb12af535fd119b2cbe17d87e9/apps/server/src/config/schema.ts#L29
However, my email service provider utilizes SSL on port 465. Despite attempting various configurations based on the nodemailer documentation available [here](https://nodemailer.com/smtp/), I encountered difficulties in sending emails through the SMTP service using the following settings:
```
smtp://username:password@smtp.example.com:465
smtp://username:password@smtp.example.com:465/?secure=true
smtp://username:password@smtp.example.com:587/?requireTLS=true
```
Upon further investigation, I found that nodemailer supports the `smtps://` …
=> feat(server): Support for SMTP-over-TLS

apps/artboard/src/templates/chikorita.tsx
Fix the Sidebar is not stretching to the full height in the Chikorita template
I added a small bug fix to get the hang of the project.
I am inspired by your work on this and am looking forward to collaborating more.
=> Bug Fix #1847 - Fix Sidebar Height in Chikorita template

apps/server/src/printer/printer.service.ts
Fixes #836 
This changes the generated PDF name from the ID to the title (e.g. Resume V34.pdf).
=> Fix: generate PDF name from title instead of id

apps/artboard/src/templates/azurill.tsx, apps/artboard/src/templates/bronzor.tsx, apps/artboard/src/templates/chikorita.tsx, apps/artboard/src/templates/ditto.tsx, apps/artboard/src/templates/gengar.tsx, apps/artboard/src/templates/glalie.tsx, apps/artboard/src/templates/kakuna.tsx, apps/artboard/src/templates/leafish.tsx, apps/artboard/src/templates/nosepass.tsx, apps/artboard/src/templates/onyx.tsx, apps/artboard/src/templates/pikachu.tsx, apps/artboard/src/templates/rhyhorn.tsx
Issue #1998
Added URL support for custom fields.
If the value of a custom field is a URL, the custom field will render as a link with the provided name as the title. If there is no name, it will show a clickable URL.
Before:
After:
=> feat(templates): added url support for custom fields

.eslintrc.json, .prettierrc
I'm using a windows machine and I needed to apply these changes in order to be able to work on the repo locally.
Setting them in the repo will support local development on windows machines, as well.
=> set endOfLine to auto to support the codebase also on windows machines

apps/client/src/pages/builder/sidebars/left/sections/picture/options.tsx
Fixes  #1953 
In profile picture edit section, when a user selects a circle border radius, clicks on the numeric input for the border radius, and then clicks outside, the `onBorderRadiusChange` function is triggered and receives an empty string (`""`) as the `value`.
So updated the code to check for empty string as being done in `onAspectRatioChange` function.
=> fix(edit profile picture): fix the page crash happening when clicking on circular border radius

apps/artboard/src/templates/azurill.tsx, apps/artboard/src/templates/chikorita.tsx, apps/artboard/src/templates/ditto.tsx, apps/artboard/src/templates/gengar.tsx, apps/artboard/src/templates/glalie.tsx, apps/artboard/src/templates/leafish.tsx, apps/artboard/src/templates/pikachu.tsx
Fixes https://github.com/AmruthPillai/Reactive-Resume/issues/2101
Adjust templates so that the main part takes full-width of the page if there is no sidebar on the page, to avoid having blank spaces
=> feat(templates): make main full-width if sidebar is empty

apps/server/src/printer/printer.service.ts
Bug: unable to print if url contains the word "localhost" in any location 
resulting in the "about:blank", no output path
example: `http://nonlocalhoster.com` would be changed to `http://nonhost.docker.internaler.com`
proposed: 
change localhost matching for local dev environments from a url string match to more specific regex that matches host property.
- Low Priority
- Edge Case
- Service resilience
=> fix(printer): refine "localhost" matching in printer.service.ts 

apps/artboard/src/templates/rhyhorn.tsx
Closes #2090 
Added right border to website if custom fields are used
Before:
After:
=> fix(templates): Add right border after website in Rhyhorn

apps/client/src/pages/dashboard/resumes/page.tsx, libs/ui/src/components/scroll-area.tsx
[Issue](https://github.com/AmruthPillai/Reactive-Resume/issues/2034)
Fixed Card clipping issue on Dashboard page in grid view. Where the sides of the card where being clipped once the hover animation is triggered. 
**BEFORE**
desktop
Mobile
**AFTER**
Desktop
Mobile
**Explanation:**
By default ScrollAreaPrimitive.Root sets the class name to 'overflow-hidden'. Then passing a classname with 'overflow-visible' to the scroll-area UI component is not enough. "ScrollAreaPrimitiv.Viewport" applies some extra default styles if the props type='scroll'. I have added a boolean prop type that allows us to disable this and allow bot overflowX and overflowY to be visible in the scenarios where we need it. 
Let me know if you need more information.
=> bugfix: Fixed clipping issue with cards on dashboard page

CONTRIBUTING.md
package.json and GitHub Actions both run with Node 20. Originally changed in 748b509b1db5725f122c463c5ad02926b80cccf4
=> fix(docs): Update CONTRIBUTING.md for Node 20

apps/artboard/src/pages/builder.tsx, apps/client/src/pages/builder/_components/toolbar.tsx, package.json, pnpm-lock.yaml
To improve UX with trackpads.
The current trackpad behaviour does not feel natural. Usually when scrolling on a trackpad using 2 fingers, the page or content would Pan; whereas Zooming is achieved by pinching 2 fingers.
On a mouse, it is arguably more user-friendly to Scroll to Zoom. Therefore, I have added a toggle button to switch between behaviours.
I opted for the default behaviour to be Scroll to Pan because there are already various methods to control the zoom levels, and I believe that panning actions are more common than zooming. For context, the default Double-click behaviour is set to Zoom In; and there are the Zoom In & Out buttons on the toolbar to control the zoom levels. Open to discussion / change.
- Add a new button to the Toolbar to handle switching between "Scroll to …
=> feat(toggle-pan): Add toggle to switch between "Scroll to Pan" and "Scroll to Zoom"

.github/ISSUE_TEMPLATE/bug-report.yml
A few themes were missing when I filled out a bug report.
=> fix(docs): Add missing themes to bug-report

libs/ui/src/components/rich-input.tsx
**Description**
This pull request addresses a bug where the "Insert Image" button and certain toolbar actions (Insert Horizontal Rule and Insert Break Line) would unintentionally trigger the submission of section_dialog
**Fixed Problem**
- Issue: The "Insert Image" button would unintentionally cause the section_dialog to submit, closing the form. (issue #1996)
- Issue: The "Insert Horizontal Rule" and "Insert Break Line" buttons in the editor toolbar would trigger the submission of section_dialog, make these buttons unusable.
**Changes Made**
1. Prevent Default Form Submission for Insert Image
Updated the InsertImageForm component to use e.stopPropagation() and e.preventDefault() in the onSubmit handler. This prevents the image insertion from causing the parent form to submit.
2. Set …
=> Fix(client): Fix Unintentional Form Submission on Rich-input Toolbar Actions
